application:
  name: 'Alternet B.V.'
  # The version will be automatically updated by a git tag in the SelfReleaseCommand!
  version: 'dev-master'
  server_admin: 'support@alternet.nl'

self:
  remote_url: 'ssh://git@source.alternet.nl:7999/devops/cli-alternet.git'
  manifest_url: 'http://cli.alternet.nl/manifest.json'
  download_url: 'http://cli.alternet.nl/download/'

hipchat:
  token: 'ByiCT5cO3WGOR03NLzvbqt9MP7m7hMVVDKEmcoCB'

composer:
  hipchat: 3329930
  satis:
    remote_url: 'ssh://git@source.alternet.nl:7999/devops/satis-alternetprivaterepository.git'
    defaults:
      name: 'Alternet Private Composer Repository'
      homepage: 'https://composer.alternet.nl'
      repositories:
      require-all: true
  available_licenses:
    - 'GPL-2.0'
    - 'GPL-2.0+'
    - 'GPL-3.0'
    - 'GPL-3.0+'
  default_vendor: 'alternet'
  license: 'GPL-3.0+'
  author:
    name: 'AlterNET B.V.'
    email: 'support@alternet.nl'
    homepage: 'https://www.alternet.nl'

bitbucket:
  endpoint: 'https://source.alternet.nl'
  default_production_branch: 'master'
  default_acceptance_branch: 'Acceptance'
  default_testing_branch: 'Testing'
  default_development_branch: 'Development'
  projects:
    all:
      options:
        create_repo:
          - 'validator_default'
          - 'excute_hipchat_integration'
          - 'execute_create_master_branch'
    DEVOPS:
      hipchat: 3087688
    T3EXT:
      satis: true
      hipchat: 3176502
      composer:
        license: 'GPL-2.0'
        default_vendor: 'tx_alternet'
        type: 'typo3-cms-extension'
      options:
        create_repo:
          - 'validator_no_app_prefix'
          - 'validator_extension_name'
          - 'wizard_create_composer_file'
    T3PACK:
      satis: true
      hipchat: 3174582
      options:
        create_repo:
          - 'validator_no_app_prefix'
          - 'validator_package_name'
          - 'wizard_create_composer_file'

bamboo:
  endpoint: 'https://cd.alternet.nl'

app:
  relative_working_directory: '.alternet'
  local:
    relative_working_directory: '.alternet/local'
  app_config:
    relative_file_path: '.alternet/app.config.yaml'
    max_search_depth: 20
  bitbucket_repository_selectors:
    - 'TYPO3'
    - 'SATIS'
    - 'CLI'