application:
  name: 'Alternet B.V.'
  version: '1.x-dev'

hipchat:
  token: 'ByiCT5cO3WGOR03NLzvbqt9MP7m7hMVVDKEmcoCB'

bitbucket:
  endpoint: 'https://source.alternet.nl'
  default_production_branch: 'master'
  default_acceptance_branch: 'Acceptance'
  default_testing_branch: 'Testing'
  default_development_branch: 'Development'
  projects:
    all:
      options:
        create_repo:
          - 'validator_default'
          - 'execute_create_master_branch'
    T3EXT:
      hipchat: 3176502
      options:
        create_repo:
          - 'validator_no_app_prefix'
          - 'validator_extension_name'
          - 'excute_hipchat_integration'
          - 'wizard_create_composer_file'
    T3PACK:
      hipchat: 3174582
      options:
        create_repo:
          - 'validator_no_app_prefix'
          - 'validator_package_name'
          - 'excute_hipchat_integration'
          - 'wizard_create_composer_file'

app:
  app_config:
    relative_file_path: '.alternet/app.config.yaml'
    max_search_depth: 20
  bitbucket_repository_selectors:
    - 'TYPO3'