# Metadata about the CLI application itself.
application:
  name: 'Alternet B.V.'
  version: '1.x-dev'

hipchat:
  token: '4RZwm3ayzNrDVma6z0493QIuHi5FhVPkwYemIkMm'
  rooms:
    - cli: 3373199

bitbucket:
  endpoint: 'https://source.alternet.nl'
  default_production_branch: 'master'
  default_acceptance_branch: 'Acceptance'
  default_testing_branch: 'Testing'
  default_development_branch: 'Development'

projects:
  config_file_path: '.alternet/app.config.yaml'
  bitbucket_repository_selectors:
    - 'TYPO3'