application:
  name: 'Alternet B.V.'
  version: '1.x-dev'
  relative_cli_working_directory: '/alternet_cli'

hipchat:
  token: 'ByiCT5cO3WGOR03NLzvbqt9MP7m7hMVVDKEmcoCB'
  rooms:
    - cli: 3373199

bitbucket:
  endpoint: 'https://source.alternet.nl'
  default_production_branch: 'master'
  default_acceptance_branch: 'Acceptance'
  default_testing_branch: 'Testing'
  default_development_branch: 'Development'

app:
  app_config:
    relative_file_path: '.alternet/app.config.yaml'
    max_search_depth: 20
  bitbucket_repository_selectors:
    - 'TYPO3'