# Metadata about the CLI application itself.
application:
  name: 'Alternet B.V.'
  version: '0.1.0'

hipchat:
  token: 'Y7CCnr9OyukxnYtnAUYGBBVjgAjNRGb3bvVspfdK'

bitbucket:
  endpoint: 'https://source.alternet.nl'