Application:
  template: 'typo3_7.6'
  key: 'zeist'
  name: 'Gemeente Zeist'
  hipchat: 3172710

Local:
  Domains:
    - 'zeist.local.alternet.nl'
    - 'centrum.zeist.local.alternet.nl'
    - 'werken-bij.zeist.local.alternet.nl'

Development:
  template: 'default'
  Domains:
    - 'zeist.development.alternet.nl'
    - 'centrum.zeist.development.alternet.nl'
    - 'werken-bij.zeist.development.alternet.nl'

Testing:
  template: 'default'
  Domains:
    - 'zeist.testing.alternet.nl'
    - 'centrum.zeist.testing.alternet.nl'
    - 'werken-bij.zeist.testing.alternet.nl'

Acceptance:
  template: 'default'
  Domains:
    - 'acc.zeist.nl'
    - 'acc.centrumzeistvernieuwt.nl'
    - 'acc.werkenbijzeist.nl'

Production:
  Domains:
    - 'www.zeist.nl'
    - 'zeist.nl'
    - 'www.centrumzeistvernieuwt.nl'
    - 'centrumzeistvernieuwt.nl'
    - 'www.werkenbijzeist.nl'
    - 'werkenbijzeist.nl'