application:
  template: 'cli_alternet'
  key: 'devops'
  name: 'Alternet CLI'
  hipchat: 3373199
  web_directory: '/web'

local:
  domains:
    - 'cli.local.alternet.nl'

development:
  template: 'default'
  domains:
    - 'cli.alternet.nl'
  git_branch: 'master'
  build:
    - 'box build'
  post_build:
    - 'sudo rm /usr/local/bin/alternet.phar'
    - 'sudo cp alternet.phar /usr/local/bin'
    - 'sudo chown -R root.root /usr/local/bin/alternet.phar'
    - 'sudo chmod 0755 /usr/local/bin/alternet.phar'